version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mojbudzet-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    command:
      - gunicorn
      - -w
      - "3"
      - -b
      - 0.0.0.0:5000
      - "app:create_app()"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mojbudzet-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8080:80"